const THEMES = [
  { title: "Mangá / anime famoso", low: "desconhecido", high: "muito famoso" },
  { title: "Esportes mais conhecidos", low: "pouca gente conhece", high: "muito popular" },
  { title: "Contos de fadas populares", low: "desconhecido", high: "popular" },
  { title: "Personagens da ficção com quem você gostaria de ter um encontro", low: "não valeria um encontro", high: "provavelmente casaria" },
  { title: "Pessoas famosas que você gostaria de ser", low: "não gostaria de ser", high: "gostaria de ser" },
  { title: "Lugares onde você gostaria de morar", low: "não ficaria lá 5 minutos", high: "passaria lá a eternidade" },
  { title: "Poderes especiais que você gostaria de ter", low: "não gostaria", high: "gostaria" },
  { title: "Filmes conhecidos", low: "ninguém viu", high: "todo mundo assistiu" },
  { title: "Coisas que te dão medo", low: "nem um sustinho", high: "morreria de medo" },
  { title: "Itens do dia a dia que poderiam ser boas armas", low: "nada demais", high: "arma forte" },
  { title: "Coisas que você não conseguiria perdoar", low: "não, obrigado", high: "imperdoável" },
  { title: "Coisas nas quais você gostaria de ficar em imersão", low: "não vale o clique", high: "quero uma piscina cheia disso" },
  { title: "Coisas que você gostaria de fotografar", low: "nem pararia pra olhar", high: "faria um book" },
  { title: "Coisas que você ficaria olhando com admiração", low: "não acreditaria", high: "ficaria olhando por horas" },
  { title: "Mentiras que você acreditaria", low: "credo, horrível!", high: "acreditaria com certeza" },
  { title: "Sabores de sorvete", low: "não é nada", high: "comeria toneladas" },
  { title: "Coisas importantes na vida", low: "não importante", high: "importantíssimo" },
  { title: "Habilidades importantes para ser líder", low: "não essencial", high: "essencial" },
  { title: "Coisas que te fazem feliz", low: "não te faz feliz", high: "felicidade pura" },
  { title: "Itens para lutar contra zumbis", low: "nada demais", high: "adiós, zumbi!" },
  { title: "Atletas famosos", low: "pouca gente conhece", high: "grande campeão" },
  { title: "Comidas famosas", low: "pouco conhecidas", high: "encontradas em todo o mundo" },
  { title: "Personagens da ficção que você gostaria de ser", low: "não seria", high: "seria muito" },
  { title: "Celebridades de filmes e séries atuais", low: "pouco conhecidas", high: "está sempre nos lançamentos" },
  { title: "Coisas que cheiram bem", low: "cheiro normal", high: "faria um perfume disso" },
  { title: "Souvenirs", low: "não faria", high: "teria mais de mil" },
  { title: "Coisas que você gostaria de fazer ao se aposentar", low: "não faria", high: "faria com toda certeza" },
  { title: "Coisas difíceis de suportar", low: "pouco difícil", high: "praticamente impossível" },
  { title: "Coisas para fazer sucesso nas mídias sociais", low: "desnecessária", high: "obrigatório" },
  { title: "Habilidades essenciais para um comediante", low: "não essencial", high: "obrigatória" },
  { title: "Coisas pesadas", low: "levinho", high: "pesado" },
  { title: "Canções famosas", low: "ninguém conhece", high: "todo mundo canta junto" },
  { title: "Figuras históricas populares", low: "vale pouco", high: "figura importante" },
  { title: "Marcas valiosas", low: "vale pouco", high: "vale bilhões" },
  { title: "Desejos de infância", low: "não quero fazer", high: "queria pra caramba" },
  { title: "Coisas que você quer fazer quando acorda", low: "não quero", high: "quero muito" },
  { title: "Itens úteis em uma casa", low: "inútil", high: "muito útil" },
  { title: "Sons que te fazem feliz", low: "não faz", high: "felicidade para os ouvidos" },
  { title: "Coisas que fazem você se sentir amado(a)", low: "cringe", high: "é puro amor" },
  { title: "O que é legal para um estudante do ensino médio", low: "não é legal", high: "super legal" },
  { title: "Presentes de aniversário comuns", low: "até eu encarava", high: "todo mundo já ganhou" },
  { title: "Vilões mais temíveis", low: "ninguém liga", high: "me faz ter pesadelos" },
  { title: "Países populares para viajar", low: "ninguém vai", high: "todo mundo já foi" },
  { title: "Coisas fofinhas", low: "pouco fofinho", high: "um cuti-cuti" },
  { title: "Coisas que te fazem feliz no amor", low: "pouco feliz", high: "muito feliz" },
  { title: "Atividades difíceis de fazer sozinho", low: "não tão difícil", high: "impossível" },
  { title: "Animais que você gostaria de montar", low: "inútil", high: "queria demais" },
  { title: "Habilidades úteis no trabalho", low: "pouco útil", high: "muito útil" },
  { title: "O que faz uma criança feliz", low: "pouco feliz", high: "isso sim é felicidade" },
  { title: "O que faz um gato feliz", low: "pouco confortável", high: "muito confortável" },
  { title: "Tamanho de animais", low: "pequeno", high: "enorme" },
  { title: "Lugares que você frequenta", low: "pouco frequente", high: "vai muito" },
  { title: "Brinquedos conhecidos", low: "desconhecido", high: "toda criança já teve" },
  { title: "Palavras que você gostaria de ouvir", low: "praticamente uma ofensa", high: "mais que um elogio" },
  { title: "Coisas leves", low: "pouco leve", high: "levíssimo" },
  { title: "Drinques populares", low: "ninguém bebe isso", high: "todo mundo já bebeu" },
  { title: "Coisas que dão sono", low: "acordadíssimo", high: "zzzzz…" },
  { title: "Veículos comuns", low: "nunca vi", high: "tem em cada esquina" },
  { title: "Frases estranhas ditas por uma criança", low: "normal", high: "muito estranho" },
  { title: "Pedidos de casamento", low: "de passar vergonha", high: "algo memorável" },
  { title: "Itens úteis no deserto", low: "não serve para nada", high: "salvaria sua vida" },
  { title: "Coisas surpreendentes que sairiam do corpo", low: "normal", high: "não dá pra imaginar" },
  { title: "Coisas surpreendentes embaixo de uma pedra", low: "algo comum", high: "algo surpreendente" },
  { title: "Itens de um baú do tesouro", low: "não gostaria", high: "queria muito" },
  { title: "Momentos históricos para visitar", low: "não iria nem pagando", high: "iria agora" },
  { title: "Alimentos que fazem bem", low: "nada saudável", high: "puro suco de saúde" },
  { title: "Coisas confiáveis", low: "pouco confiável", high: "confiável eternamente" },
  { title: "Festivais para participar", low: "flopou", high: "gastaria o salário pra ir" },
  { title: "Heróis que um vilão não gostaria de enfrentar", low: "não gostaria", high: "tenho medo até da sombra" },
  { title: "Descobertas científicas", low: "não gostaria de descobrir", high: "merece um Nobel" },
  { title: "Itens para levar à ilha deserta", low: "não útil", high: "muito útil" },
  { title: "Jogos de tabuleiro", low: "aquele que flopou", high: "digno de prêmio" },
  { title: "Piadas engraçadas", low: "isso é ofensivo", high: "ri litros" },
  { title: "Itens diferentões", low: "nada interessante", high: "isso é muito legal" },
  { title: "Nomes de golpes especiais", low: "não botou medo", high: "isso sim impõe respeito" },
  { title: "Características de amizades", low: "ninguém se importa", high: "BFF na certa" },
  { title: "Títulos de livros", low: "feitiço comum", high: "vou comprar" },
  { title: "Feitiços favoritos de mago", low: "nada", high: "usaria toda hora" },
  { title: "O que faz um cachorro feliz", low: "nada AU-AU-dacioso", high: "de balançar a cauda" },
  { title: "Coisas surpreendentes ditas por um professor", low: "faz parte da aula", high: "por essa ninguém esperava" },
  { title: "As coisas mais bonitas do mundo", low: "ok", high: "visão do paraíso" },
  { title: "Coisas populares com crianças", low: "pouco conhecida", high: "muito famosa" },
  { title: "Doces conhecidos", low: "nunca vi", high: "vende em todo lugar" },
  { title: "Nomes legais", low: "muito comum", high: "meu filho vai ter" },
  { title: "Amor verdadeiro ou aventura", low: "aventura", high: "amor verdadeiro" },
  { title: "Coisas que você faz de bom humor", low: "nunca faço", high: "faço muito" },
  { title: "Pose de herói", low: "um desânimo só", high: "épica" },
  { title: "Lugares que animam um explorador", low: "não gostaria", high: "bora lá agora" },
  { title: "Mundos imaginários", low: "inútil", high: "viveria lá o resto da vida" },
  { title: "Habilidades úteis em relacionamentos", low: "fraco demais", high: "essencial" },
  { title: "Personagens fortes da ficção", low: "nada feliz", high: "indestrutível" },
  { title: "Coisas felizes de encontrar no bolso", low: "nada feliz", high: "alegria pura" },
  { title: "Lugares de encontros românticos", low: "poucos encontros", high: "está acontecendo um agora" },
  { title: "Caretas engraçadas", low: "não engraçada", high: "muito engraçada" },
  { title: "Um prato para comer até o fim da vida", low: "não escolheria", high: "comeria agora" },
  { title: "Atos de coragem", low: "nada corajoso", high: "pura coragem" },
  { title: "O que seria ruim numa aula", low: "de boas", high: "que vergonha!" },
  { title: "Alter ego", low: "não gostaria", high: "é meu tipo" },
  { title: "Personagens com piores temperamentos", low: "desnecessária", high: "explosivo" },
  { title: "Habilidades importantes para streamers", low: "não importante", high: "obrigatória" },
  { title: "Coisas para fazer na hora H", low: "aff, nem", high: "putz, amo" }
];

function getRandomTheme() {
  const index = Math.floor(Math.random() * THEMES.length);
  return THEMES[index];
}

module.exports = { THEMES, getRandomTheme };
